# 1. Importing Dependencies

In [3]:
import os 
import gym #for building environments
from stable_baselines3 import A2C#Selected a one basic model for it 
from stable_baselines3.common.vec_env import VecFrameStack#mostly open Ai gym allows you to train on multiple environment right now with 4 envs
from stable_baselines3.common.evaluation import evaluate_policy #for Evaluation of Policy
from stable_baselines3.common.env_util import  make_atari_env

# 2. Test Environment

In [27]:
#we have lot of dependencies issue but don't worry we have all things in requirements.txt

In [44]:
env = gym.make('Breakout-v0')

C:\Users\hp\AppData\Local\Programs\Python\Python37\lib\site-packages\gym\logger.py:34: UserWarning: WARN: obs_type "image" should be replaced with the image type, one of: rgb, grayscale
  warnings.warn(colorize("%s: %s" % ("WARN", msg % args), "yellow"))


In [46]:
episodes = 5
for episode in range(1, episodes+1):
    state = env.reset()
    done = False
    score = 0 
    
    while not done:
        env.render()
        action = env.action_space.sample()
        n_state, reward, done, info = env.step(action)

        score+=reward
    print('Episode:{} Score:{}'.format(episode, score))
env.close()

Episode:1 Score:3.0
Episode:2 Score:2.0
Episode:3 Score:2.0
Episode:4 Score:2.0
Episode:5 Score:0.0


In [43]:
env.action_space #contains 18 discrete values and 
env.close()  

In [33]:
env.observation_space #contains and image of size (210, 160,3)

Box([[[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 ...

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]], [[[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 ...

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
 

# Vectorizing Environment and Training Model

In [35]:
#Vectorization means simply run multiple models at same time to learn quickly via interactions
#it allows to train agent faster by training in parallet

In [5]:
env = make_atari_env('Breakout-v0', n_envs=4, seed=0)
env = VecFrameStack(env, n_stack=4)

C:\Users\hp\AppData\Local\Programs\Python\Python37\lib\site-packages\ale_py\roms\utils.py:90: DeprecationWarning: SelectableGroups dict interface is deprecated. Use select.
  for external in metadata.entry_points().get(self.group, []):
C:\Users\hp\AppData\Local\Programs\Python\Python37\lib\site-packages\ale_py\roms\__init__.py:94: DeprecationWarning: Automatic importing of atari-py roms won't be supported in future releases of ale-py. Please migrate over to using `ale-import-roms` OR an ALE-supported ROM package. To make this warning disappear you can run `ale-import-roms --import-from-pkg atari_py.atari_roms`.For more information see: https://github.com/mgbellemare/Arcade-Learning-Environment#rom-management
  _RESOLVED_ROMS = _resolve_roms()
C:\Users\hp\AppData\Local\Programs\Python\Python37\lib\site-packages\gym\logger.py:34: UserWarning: WARN: obs_type "image" should be replaced with the image type, one of: rgb, grayscale
  warnings.warn(colorize("%s: %s" % ("WARN", msg % args), "ye

In [3]:
env.reset()

array([[[[0, 0, 0, 0],
         [0, 0, 0, 0],
         [0, 0, 0, 0],
         ...,
         [0, 0, 0, 0],
         [0, 0, 0, 0],
         [0, 0, 0, 0]],

        [[0, 0, 0, 0],
         [0, 0, 0, 0],
         [0, 0, 0, 0],
         ...,
         [0, 0, 0, 0],
         [0, 0, 0, 0],
         [0, 0, 0, 0]],

        [[0, 0, 0, 0],
         [0, 0, 0, 0],
         [0, 0, 0, 0],
         ...,
         [0, 0, 0, 0],
         [0, 0, 0, 0],
         [0, 0, 0, 0]],

        ...,

        [[0, 0, 0, 0],
         [0, 0, 0, 0],
         [0, 0, 0, 0],
         ...,
         [0, 0, 0, 0],
         [0, 0, 0, 0],
         [0, 0, 0, 0]],

        [[0, 0, 0, 0],
         [0, 0, 0, 0],
         [0, 0, 0, 0],
         ...,
         [0, 0, 0, 0],
         [0, 0, 0, 0],
         [0, 0, 0, 0]],

        [[0, 0, 0, 0],
         [0, 0, 0, 0],
         [0, 0, 0, 0],
         ...,
         [0, 0, 0, 0],
         [0, 0, 0, 0],
         [0, 0, 0, 0]]],


       [[[0, 0, 0, 0],
         [0, 0, 0, 0],
         [0, 0

In [1]:
#env.render()  to show we have four simulated environment

In [5]:
env.close()

In [7]:


log_path = os.path.join('Training', 'Logs')

model = A2C('CnnPolicy', env, verbose=1, tensorboard_log=log_path)

Using cpu device
Wrapping the env in a VecTransposeImage.


In [8]:
model.learn(total_timesteps=400000)

C:\Users\hp\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow\python\framework\dtypes.py:516: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
C:\Users\hp\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow\python\framework\dtypes.py:517: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
C:\Users\hp\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow\python\framework\dtypes.py:518: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
C:\Users\hp\AppData\Local\Pr

Logging to Training\Logs\A2C_2
------------------------------------
| rollout/              |          |
|    ep_len_mean        | 171      |
|    ep_rew_mean        | 1.42     |
| time/                 |          |
|    fps                | 69       |
|    iterations         | 100      |
|    time_elapsed       | 28       |
|    total_timesteps    | 2000     |
| train/                |          |
|    entropy_loss       | -2.85    |
|    explained_variance | 0.238    |
|    learning_rate      | 0.0007   |
|    n_updates          | 99       |
|    policy_loss        | 0.26     |
|    value_loss         | 0.375    |
------------------------------------
------------------------------------
| rollout/              |          |
|    ep_len_mean        | 167      |
|    ep_rew_mean        | 1.34     |
| time/                 |          |
|    fps                | 75       |
|    iterations         | 200      |
|    time_elapsed       | 52       |
|    total_timesteps    | 4000     |
| train

# Saving Model

In [9]:
a2c_path = os.path.join('Training', 'Saved Models','A2C_Breakout_Model')
model.save(a2c_path)

In [10]:
del model

In [11]:
model = A2C.load(a2c_path, env)

Wrapping the env in a VecTransposeImage.



# 5. Evaluate and Test

In [12]:
env = make_atari_env('Breakout-v0', n_envs=1, seed=0)#we make this because evaluation of environment requires 
env = VecFrameStack(env, n_stack=4)

C:\Users\hp\AppData\Local\Programs\Python\Python37\lib\site-packages\gym\logger.py:34: UserWarning: WARN: obs_type "image" should be replaced with the image type, one of: rgb, grayscale
  warnings.warn(colorize("%s: %s" % ("WARN", msg % args), "yellow"))


In [13]:
evaluate_policy(model, env, n_eval_episodes=10 ,render=True)

C:\Users\hp\AppData\Local\Programs\Python\Python37\lib\site-packages\gym\logger.py:34: UserWarning: WARN: We strongly suggest supplying `render_mode` when constructing your environment, e.g., gym.make(ID, render_mode='human'). Using `render_mode` provides access to proper scaling, audio support, and proper framerates.
  warnings.warn(colorize("%s: %s" % ("WARN", msg % args), "yellow"))


(11.1, 3.269556544854363)

In [14]:
env.close()