# 1 Install Stable Baselines

In [1]:
#!pip install stable-baselines3[extra]

In [1]:
import os 
import gym #for building environments
from stable_baselines3 import PPO#Selected a one basic model for it 
from stable_baselines3.common.vec_env import DummyVecEnv#mostly open Ai gym allows you to train on multiple environment this is the wrapper function
from stable_baselines3.common.evaluation import evaluate_policy #for Evaluation of Policy

<!-- Вox :n dimensional tensor, range of values
E.g. Box (0,1,shape=(3,3))
Discrete :- set of items
E.g. Discrete (3)
Tuple - tuple of other spaces e.g.Box or Discrete
E.g. Tuple ( (Discrete (2), Box (0,100, shape= (1,))))
Dict - dictionary of spaces e.g. Box or Discrete
E.g. Dict: ({'height':Discrete (2), "speed":Box (0,100, shape= (1, )) })
MultiBinary one hot encoded binary values
E.g. MultiBinary(4)
MultiDiscrete - multiple discrete value
Eg. MultiDiscrete([2,4,2])

# 2. Load an Environment

In [2]:
environment_name = 'CartPole-v0'
env = gym.make(environment_name)

In [6]:
environment_name

'CartPole-v0'

In [15]:
episodes = 5
for episode in range(1, episodes+1):
    state = env.reset()#Initial observations
    done = False
    score =0

    while not done:
        env.render()#view environment
        action = env.action_space.sample()#pick action from action space
        n_states,reward,done,info = env.step(action)#apply action to the environment 
        score +=reward
    print('Episode: {} Score: {}'.format(episode,score))
env.close()#close environment







Episode: 1 Score: 35.0
Episode: 2 Score: 11.0
Episode: 3 Score: 17.0
Episode: 4 Score: 12.0
Episode: 5 Score: 46.0


In [16]:
#Episode is like a full game the limit of some models for 1 episode is fixed like 200 frames for CartPole but some has this varibale

# 3 Understanding Environmnet

In [17]:
# env.action_space# this tells action type
# env.action_space.sample()#it gives (0 or 1 ) because we have 2 discrete values zero and one action zero left action 1 right   

In [24]:
env.observation_space
env.observation_space.sample()
#1 cart position cart velocity pole angle pole angular velocity

array([-4.4787750e+00, -2.7301290e+37, -1.2654702e-01, -1.6757597e+38],
      dtype=float32)

In [20]:
env.reset()

array([-0.01098211,  0.01933999,  0.02342481,  0.01444309])

In [21]:
env.step(1)

(array([-0.01059531,  0.2141183 ,  0.02371367, -0.27075796]), 1.0, False, {})

# 4 Training a model

In [9]:
#make directory first
log_path = os.path.join('Training','Logs')


In [10]:
log_path

'Training\\Logs'

In [8]:
env = gym.make(environment_name)
env = DummyVecEnv([lambda: env])#wrapped our environment 
model = PPO('MlpPolicy',env, verbose=1, tensorboard_log=log_path)

Using cpu device


In [9]:
model.learn(total_timesteps=20000)

C:\Users\hp\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow\python\framework\dtypes.py:516: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
C:\Users\hp\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow\python\framework\dtypes.py:517: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
C:\Users\hp\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow\python\framework\dtypes.py:518: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
C:\Users\hp\AppData\Local\Pr

Logging to Training\Logs\PPO_1
-----------------------------
| time/              |      |
|    fps             | 298  |
|    iterations      | 1    |
|    time_elapsed    | 6    |
|    total_timesteps | 2048 |
-----------------------------
-----------------------------------------
| time/                   |             |
|    fps                  | 399         |
|    iterations           | 2           |
|    time_elapsed         | 10          |
|    total_timesteps      | 4096        |
| train/                  |             |
|    approx_kl            | 0.009219332 |
|    clip_fraction        | 0.109       |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.686      |
|    explained_variance   | -0.00669    |
|    learning_rate        | 0.0003      |
|    loss                 | 7.05        |
|    n_updates            | 10          |
|    policy_gradient_loss | -0.0176     |
|    value_loss           | 57.2        |
-----------------------------------------
---

# 5. Save Model

In [3]:
PPO_PATH = os.path.join('Training','Logs','PPO_MODEL_MY_CARTPOLE')

In [11]:
model.save(PPO_PATH)

In [12]:
del model

In [4]:
#load saved model
model = PPO.load(PPO_PATH , env=env)

Wrapping the env with a `Monitor` wrapper
Wrapping the env in a DummyVecEnv.


# 6. Evaluate model


In [7]:
evaluate_policy(model, env, n_eval_episodes=10, render=True)#return avearage and standard deviation

C:\Users\hp\AppData\Local\Programs\Python\Python37\lib\site-packages\stable_baselines3\common\evaluation.py:69: UserWarning: Evaluation environment is not wrapped with a ``Monitor`` wrapper. This may result in reporting modified episode lengths and rewards, if other wrappers happen to modify these. Consider wrapping environment first with ``Monitor`` wrapper.
  UserWarning,


(200.0, 0.0)

# 7. Test Model

In [7]:
episodes = 5
for episode in range(1, episodes+1):
    obs = env.reset()#Initial observations
    done = False
    score =0

    while not done:
        env.render()#view environment
        action, _ = model.predict(obs) #we use model to do cartpole now
        obs,reward,done,info = env.step(action)#apply action to the environment 
        score +=reward
    print('Episode: {} Score: {}'.format(episode,score))
env.close()#close environment


Episode: 1 Score: 200.0
Episode: 2 Score: 200.0
Episode: 3 Score: 200.0
Episode: 4 Score: 200.0
Episode: 5 Score: 200.0


In [8]:
#200 score comes because reward for one action is is 1 (when pole not fall) and 0 when fall so the return or score is sum of rewards
#These are model less environment

# 8. Viewing logs on Tensorboard

In [11]:
training_log_path = os.path.join(log_path, 'PPO_1')

In [12]:
training_log_path

'Training\\Logs\\PPO_1'

# 9 Adding Callback to the training Stage

In [5]:
from stable_baselines3.common.callbacks import EvalCallback, StopTrainingOnRewardThreshold

In [6]:
save_path = os.path.join('Training','Saved Models')

In [7]:
stop_callbacks = StopTrainingOnRewardThreshold(reward_threshold=200, verbose=1)
eval_callback = EvalCallback(env,callback_on_new_best=stop_callbacks,eval_freq=10000, best_model_save_path=save_path, verbose=1)

In [12]:
model = PPO('MlpPolicy',env, verbose=1, tensorboard_log=log_path)

Using cpu device
Wrapping the env with a `Monitor` wrapper
Wrapping the env in a DummyVecEnv.


In [13]:
model.learn(total_timesteps=20000, callback = eval_callback)

C:\Users\hp\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow\python\framework\dtypes.py:516: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
C:\Users\hp\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow\python\framework\dtypes.py:517: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
C:\Users\hp\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow\python\framework\dtypes.py:518: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
C:\Users\hp\AppData\Local\Pr

Logging to Training\Logs\PPO_2
---------------------------------
| rollout/           |          |
|    ep_len_mean     | 21.3     |
|    ep_rew_mean     | 21.3     |
| time/              |          |
|    fps             | 203      |
|    iterations      | 1        |
|    time_elapsed    | 10       |
|    total_timesteps | 2048     |
---------------------------------
-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 26          |
|    ep_rew_mean          | 26          |
| time/                   |             |
|    fps                  | 313         |
|    iterations           | 2           |
|    time_elapsed         | 13          |
|    total_timesteps      | 4096        |
| train/                  |             |
|    approx_kl            | 0.008237669 |
|    clip_fraction        | 0.0912      |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.686      |
|    explained_variance   | 0.000714    |

C:\Users\hp\AppData\Local\Programs\Python\Python37\lib\site-packages\stable_baselines3\common\evaluation.py:69: UserWarning: Evaluation environment is not wrapped with a ``Monitor`` wrapper. This may result in reporting modified episode lengths and rewards, if other wrappers happen to modify these. Consider wrapping environment first with ``Monitor`` wrapper.
  UserWarning,


Eval num_timesteps=10000, episode_reward=170.80 +/- 24.59
Episode length: 170.80 +/- 24.59
------------------------------------------
| eval/                   |              |
|    mean_ep_length       | 171          |
|    mean_reward          | 171          |
| time/                   |              |
|    total_timesteps      | 10000        |
| train/                  |              |
|    approx_kl            | 0.0071648173 |
|    clip_fraction        | 0.0675       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.605       |
|    explained_variance   | 0.303        |
|    learning_rate        | 0.0003       |
|    loss                 | 19.9         |
|    n_updates            | 40           |
|    policy_gradient_loss | -0.0164      |
|    value_loss           | 58.8         |
------------------------------------------
New best mean reward!
---------------------------------
| rollout/           |          |
|    ep_len_mean     | 57.2     |
|    ep_rew

# 10 Changing the Policy

In [14]:
net_arch = [dict(pi=[128,128,128,128], vf=[128,128,128,128])]

In [15]:
model = PPO('MlpPolicy', env, verbose=1, tensorboard_log=log_path, policy_kwargs={'net_arch':net_arch})

Using cpu device
Wrapping the env with a `Monitor` wrapper
Wrapping the env in a DummyVecEnv.


In [16]:
model.learn(total_timesteps=20000, callback=eval_callback)

Logging to Training\Logs\PPO_3
---------------------------------
| rollout/           |          |
|    ep_len_mean     | 21       |
|    ep_rew_mean     | 21       |
| time/              |          |
|    fps             | 686      |
|    iterations      | 1        |
|    time_elapsed    | 2        |
|    total_timesteps | 2048     |
---------------------------------
-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 29.8        |
|    ep_rew_mean          | 29.8        |
| time/                   |             |
|    fps                  | 546         |
|    iterations           | 2           |
|    time_elapsed         | 7           |
|    total_timesteps      | 4096        |
| train/                  |             |
|    approx_kl            | 0.014992548 |
|    clip_fraction        | 0.208       |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.681      |
|    explained_variance   | 0.00113     |

C:\Users\hp\AppData\Local\Programs\Python\Python37\lib\site-packages\stable_baselines3\common\evaluation.py:69: UserWarning: Evaluation environment is not wrapped with a ``Monitor`` wrapper. This may result in reporting modified episode lengths and rewards, if other wrappers happen to modify these. Consider wrapping environment first with ``Monitor`` wrapper.
  UserWarning,


Eval num_timesteps=10000, episode_reward=200.00 +/- 0.00
Episode length: 200.00 +/- 0.00
-----------------------------------------
| eval/                   |             |
|    mean_ep_length       | 200         |
|    mean_reward          | 200         |
| time/                   |             |
|    total_timesteps      | 10000       |
| train/                  |             |
|    approx_kl            | 0.012616446 |
|    clip_fraction        | 0.124       |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.563      |
|    explained_variance   | 0.433       |
|    learning_rate        | 0.0003      |
|    loss                 | 25.3        |
|    n_updates            | 40          |
|    policy_gradient_loss | -0.0184     |
|    value_loss           | 55.1        |
-----------------------------------------
---------------------------------
| rollout/           |          |
|    ep_len_mean     | 77       |
|    ep_rew_mean     | 77       |
| time/            

# 11 Using Alternate model beside PPO

In [17]:
from stable_baselines3 import A2C

In [18]:
model = A2C('MlpPolicy', env, verbose=1, tensorboard_log=log_path)

Using cpu device
Wrapping the env with a `Monitor` wrapper
Wrapping the env in a DummyVecEnv.


In [19]:
model.learn(total_timesteps=20000)

Logging to Training\Logs\A2C_1
------------------------------------
| rollout/              |          |
|    ep_len_mean        | 30.1     |
|    ep_rew_mean        | 30.1     |
| time/                 |          |
|    fps                | 544      |
|    iterations         | 100      |
|    time_elapsed       | 0        |
|    total_timesteps    | 500      |
| train/                |          |
|    entropy_loss       | -0.669   |
|    explained_variance | 0.115    |
|    learning_rate      | 0.0007   |
|    n_updates          | 99       |
|    policy_loss        | 1.88     |
|    value_loss         | 9.16     |
------------------------------------
------------------------------------
| rollout/              |          |
|    ep_len_mean        | 45.2     |
|    ep_rew_mean        | 45.2     |
| time/                 |          |
|    fps                | 566      |
|    iterations         | 200      |
|    time_elapsed       | 1        |
|    total_timesteps    | 1000     |
| train