In [1]:
#now need to install few dependencies for car environment
# !pip install gym[box2d] pyglet

In [2]:
# Necessary Imports
import os
import gym
from stable_baselines3 import PPO
from stable_baselines3.common.evaluation import evaluate_policy
from stable_baselines3.common.vec_env import DummyVecEnv


# Test Environment

In [3]:
environment_name = "CarRacing-v0"
env = gym.make(environment_name)

In [4]:
env.action_space

Box([-1.  0.  0.], [1. 1. 1.], (3,), float32)

In [5]:
env.observation_space

Box([[[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 ...

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]], [[[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 ...

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
 

In [8]:
env.render()

True

In [5]:
env.reset()

Track generation: 1231..1541 -> 310-tiles track


array([[[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        ...,
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        ...,
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        ...,
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       ...,

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        ...,
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        ...,
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        ...,
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]]], dtype=uint8)

In [7]:
episodes = 5
for episode in range(1, episodes+1):
    state = env.reset()
    done = False
    score = 0 
    
    while not done:
        env.render()
        action = env.action_space.sample()
        n_state, reward, done, info = env.step(action)
        score+=reward
    print('Episode:{} Score:{}'.format(episode, score))
env.close()

Track generation: 1052..1319 -> 267-tiles track
Episode:1 Score:-24.81203007518831
Track generation: 1111..1393 -> 282-tiles track
Episode:2 Score:-28.825622775801076
Track generation: 1160..1463 -> 303-tiles track
Episode:3 Score:-33.77483443708663
Track generation: 1108..1389 -> 281-tiles track
Episode:4 Score:-28.571428571428864
Track generation: 1064..1338 -> 274-tiles track
Episode:5 Score:-26.73992673992708


# Train Environment

In [6]:
log_path = os.path.join('Training', 'Logs')
model = PPO("CnnPolicy", env, verbose=1, tensorboard_log=log_path)
model.learn(total_timesteps=40000)

Using cpu device
Wrapping the env with a `Monitor` wrapper
Wrapping the env in a DummyVecEnv.
Wrapping the env in a VecTransposeImage.
Track generation: 1003..1266 -> 263-tiles track


C:\Users\hp\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow\python\framework\dtypes.py:516: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
C:\Users\hp\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow\python\framework\dtypes.py:517: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
C:\Users\hp\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow\python\framework\dtypes.py:518: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
C:\Users\hp\AppData\Local\Pr

Logging to Training\Logs\PPO_4
Track generation: 1216..1524 -> 308-tiles track
Track generation: 1021..1288 -> 267-tiles track
---------------------------------
| rollout/           |          |
|    ep_len_mean     | 1e+03    |
|    ep_rew_mean     | -55.6    |
| time/              |          |
|    fps             | 109      |
|    iterations      | 1        |
|    time_elapsed    | 18       |
|    total_timesteps | 2048     |
---------------------------------
Track generation: 1155..1448 -> 293-tiles track
Track generation: 1105..1385 -> 280-tiles track
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 1e+03        |
|    ep_rew_mean          | -51.8        |
| time/                   |              |
|    fps                  | 64           |
|    iterations           | 2            |
|    time_elapsed         | 63           |
|    total_timesteps      | 4096         |
| train/                  |              |
|    ap

# Save Model

In [8]:
save_path = os.path.join("Training" , "Saved Models", "CarRacing")
model.save(save_path)

In [9]:
del model

In [11]:
model = PPO.load(save_path, env=env)

Wrapping the env with a `Monitor` wrapper
Wrapping the env in a DummyVecEnv.
Wrapping the env in a VecTransposeImage.


# Evaluate Policy

In [12]:
evaluate_policy(model, env, n_eval_episodes=50, render=True)#return avearage and standard deviation

C:\Users\hp\AppData\Local\Programs\Python\Python37\lib\site-packages\stable_baselines3\common\evaluation.py:69: UserWarning: Evaluation environment is not wrapped with a ``Monitor`` wrapper. This may result in reporting modified episode lengths and rewards, if other wrappers happen to modify these. Consider wrapping environment first with ``Monitor`` wrapper.
  UserWarning,


Track generation: 1112..1394 -> 282-tiles track
Track generation: 1088..1369 -> 281-tiles track
Track generation: 1006..1269 -> 263-tiles track
Track generation: 1015..1280 -> 265-tiles track
Track generation: 1028..1289 -> 261-tiles track
Track generation: 1132..1419 -> 287-tiles track
Track generation: 1238..1560 -> 322-tiles track
Track generation: 1270..1592 -> 322-tiles track
Track generation: 1160..1454 -> 294-tiles track
Track generation: 1072..1354 -> 282-tiles track
Track generation: 1092..1369 -> 277-tiles track
Track generation: 1183..1483 -> 300-tiles track
Track generation: 1143..1433 -> 290-tiles track
Track generation: 1201..1506 -> 305-tiles track
Track generation: 1084..1359 -> 275-tiles track
Track generation: 1115..1398 -> 283-tiles track
Track generation: 1253..1570 -> 317-tiles track
Track generation: 967..1213 -> 246-tiles track
Track generation: 1024..1284 -> 260-tiles track
Track generation: 1271..1593 -> 322-tiles track
Track generation: 1271..1593 -> 322-tiles

(-45.56548711925745, 11.890004758678938)

In [13]:
env.close()